title: Tech Illuminato blog
description: Questo blog parla della vita vista in chiave tech, spiegare cose difficili in modo facile!
baseurl: ""
url: "https://DemPago.github.io"

markdown: kramdown

permalink: /:title/
